import type { Metadata } from "next";
import { Syne, Inter } from "next/font/google";
import "./globals.css";
import ClientEffects from "@/components/layout/ClientEffects";

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${syne.variable} ${inter.variable} antialiased`}>
        <ClientEffects />
        {children}
      </body>
    </html>
  );
}
